### ISSUE TITLE
[Feature] Show all available features in state

### ISSUE THREAD

**Issue by kilian579** [GrandMoff100/HomeAssistantAPI#167]
**Is your feature request related to a problem? Please describe.**
The get_state() method for an entity of domain "light" only contains the attribute "brightness", when the light is turned on. However "brightness" is not contained in state.attributes, when the light is turned off. I guess attributes is only meant to contain "extra attributes" and not standard attributes such as "brightness". But a light I own does not support "brightness". Therefore I would like to read out a full list of available attributes for an entity.

**Describe the solution you'd like**
get_state().attributes should contain all available attributes of an entity, also when the entity is turned off

**Comment by GrandMoff100** [comment]
Hi! I believe you can do this already by accessing `.get_state().attributes` which a dictionary of the attributes of an entity state from your homeassistant's api.

**Comment by kilian579** [comment]
This is not working reliably, as i tried to explain.

I have an entity of the domain "[light](https://developers.home-assistant.io/docs/core/entity/light)" and the "brightness" attribute is not always included in the dictionary returned by `.get_state().attributes`.

It seems to be only included when the light is turned on and sometimes not even when the light is turned on, but only if the "brightness" was changed recently.

Example, two states received from the same entity:

1
```
State(
    entity_id='light.xyz', 
    state='on', 
    attributes={
        'min_color_temp_kelvin': 2000, 
        'max_color_temp_kelvin': 6535, 
        'min_mireds': 153, 
        'max_mireds': 500, 
        'supported_color_modes': ['color_temp', 'xy'], 
        'color_mode': 'color_temp', 
        'brightness': 92, 
        'color_temp_kelvin': 2500, 
        'color_temp': 400, 
        'hs_color': [28.874, 72.522], 
        'rgb_color': [255, 159, 70], 
        'xy_color': [0.546, 0.389], 
        'mode': 'normal', 
        'dynamics': 'none', 
        'friendly_name': 'X Y Z', 
        'supported_features': 40
    }, last_changed=datetime.datetime(2023, 12, 8, 16, 4, 45, 673240, tzinfo=datetime.timezone.utc), last_updated=datetime.datetime(2023, 12, 8, 16, 10, 14, 203878, tzinfo=datetime.timezone.utc), context=Context(id='01HH5336PCT9WC7YWKHM9HDFH4')
    )
```

2
```
State(
    entity_id='light.xyz', 
    state='off', 
    attributes={
        'min_color_temp_kelvin': 2000, 
        'max_color_temp_kelvin': 6535, 
        'min_mireds': 153, 
        'max_mireds': 500, 
        'supported_color_modes': ['color_temp', 'xy'], 
        'mode': 'normal', 
        'dynamics': 'none', 
        'friendly_name': 'X Y Z', 
        'supported_features': 40
    }, last_changed=datetime.datetime(2023, 12, 8, 15, 24, 56, 722575, tzinfo=datetime.timezone.utc), last_updated=datetime.datetime(2023, 12, 8, 15, 24, 56, 722575, tzinfo=datetime.timezone.utc), context=Context(id='01HH50G90J8D32S7X319RNW3MN')
    )
```

**Comment by GrandMoff100** [comment]
Ah I see. Interesting. Well if there aren't any other attributes in that dictionary that of interest then it's the API's fault since it's not sending that brightness value. I'd have to investigate the homeassistant source code some more to try to diagnose why that's happening. However there's a couple things I think you can do off the top of my head:

(a) You could cache the brightness value. That way when the api doesn't return it you can rely on the most recently returned brightness value.

(b) If `.get_state()` won't return the brightness value, and you don't have a previous one cached already you can call `entity.get_history().states` which is a tuple of historical `State`'s of the light, assuming you've enabled the `history` component in your homeassistant config. (I believe it's usually already enabled by `default_config:`). You can then grab the most recent state (which should have a brightness attribute?) of the bulb from that tuple by sorting them by `last_changed` or `last_updated` (They may already be sorted, I forget how homeassistant formats the state objects in the response).

Let me know if any of these work for you. I'm here if you run into any other issues.

**Comment by GrandMoff100** [comment]
At least one of the states in the history should have a brightness value. You can just find the most recent lightbulb state in the history that does have it (i.e. like case 1 that you sent), which logically "should" be the current state of the bulb barring that homeassistant isn't as reliable as we're expecting.

**Comment by GrandMoff100** [comment]
Closing this unless there are more issues here
