### ISSUE TITLE
[Windows] Invalid request url caused by os.path.join

### ISSUE THREAD

**Issue by kennyboy55** [GrandMoff100/HomeAssistantAPI#96]
https://github.com/GrandMoff100/HomeAssistantAPI/blob/3f5557b45605b4f68cce98d799556aecb05665b4/homeassistant_api/rawclient.py#L206

When using this library on windows, os.path.join will use backslashes, creating an invalid request url.
`https://<homeassistant>/api/services%5Clight%5Ctoggle`

**Comment by GrandMoff100** [comment]
Wow! Thank you for letting me know about this. It totally slipped my mind. I just need to switch `os.path.join` with a url joining function from `urllib`. This should be fixed with a new post release later today!

Let me know tomorrow if this issue is fixed in the next post release after today.

Thanks!
